# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Kata CI pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: 🛠️ install libs
        run: npm install
      - name: 🕵🏻 check Linter smells
        run: npm run lint
      - name: 🧪 Unit tests and Coverage
        run: npm test
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Hadolint
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          # ignore warnings (but still fail on errors) from hadolint
          error_level: 1
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tictactoeattempt1:latest
      - name: 🛠️ install chef inspec
        uses: actionshub/chef-install@main
        with:
          channel: current
          project: inspec
      - name: set chef inspec license
        run: inspec exec --chef-license-key "free-dc26fcf2-a3da-4300-a7b5-984bee02f605-5281"
      - name: ✍️ accept chef inspec license
        run: inspec exec --chef-license accept
      - name: 🧑‍🍳 inspec dockerfile
        run: npm run inspec

  # container:
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [18.x]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         # Disabling shallow clone is recommended for improving relevancy of reporting
  #         fetch-depth: 0
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: "npm"
  #     - uses: hadolint/hadolint-action@v3.1.0
  #       with:
  #         dockerfile: ./Dockerfile
  #     - name: 🛠️ install libs
  #       run: npm install

  #     - name: 🈵 hadolint
  #       run: npm run hadolint
  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
  #       with:
  #         context: .
  #         file: ./Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/tictactoeattempt1:latest
  #     - name: 🫙 container structure test
  #       run: npm run container-structure-test
  #     - name: 🤿 dive
  #       run: npm run dive
  #     - name: 💻 trivy
  #       run: npm run trivy
  #     - name: 🐙 docker compose
  #       uses: adambirds/docker-compose-action@v1.3.0
  #       with:
  #         compose-file: "./docker-compose.yml"
  #         down-flags: "--project-name tictactoestack"
  #         services: |
  #           tictactoe
  #         test-container: newman
  #         test-command: "npm test"
